EXERCISE_NONE        = "NO"
EXERCISE_BI          = "BI"
EXERCISE_DIRECTIONAL = "DI"
EXERCISE_BALANCE     = "BA"
EXERCISE_ROTATION    = "RO"

COMMAND_NONE      = 0
COMMAND_PARAMETER = 1
COMMAND_START     = 2
COMMAND_STOP      = 3
