# Generated by Django 2.2.6 on 2019-10-18 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdTable',
            new_name='OutfitId',
        ),
    ]
