# Generated by Django 2.2.6 on 2019-10-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20191018_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultData',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('exercise', models.CharField(max_length=32)),
                ('level', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fileName', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='outfitid',
            name='uuid',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
