# Generated by Django 2.2.6 on 2019-10-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20191018_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
