# Generated by Django 2.2.6 on 2019-10-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20191018_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
