# Generated by Django 2.2.6 on 2019-10-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20191018_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
